### ISSUE TITLE
Audit which chords are considered In-Key

### ISSUE THREAD

**Issue by davidforrest** [1aurend/music51#127]
For example, III+ in minor is a holdover from previous versions of the app, but now it feels pretty weird to call this "In-Key" when it shows up.

**Comment by davidforrest** [comment]
<img width="1129" alt="+III minor is in key" src="https://user-images.githubusercontent.com/4973062/75374097-7fb75180-5880-11ea-9b82-dea8f4cfeb3e.png">

**Comment by jsbean** [comment]
Kate confirmed that this was ok this morning.

**Comment by jsbean** [comment]
As such, I am going to close this up.
