### ISSUE TITLE
Investigate no correct answer

### ISSUE THREAD

**Issue by davidforrest** [1aurend/music51#130]
@1aurend slacked this--disregard if it's already fixed or tracked elsewhere:
<img width="536" alt="no right answer" src="https://user-images.githubusercontent.com/4973062/75374605-72e72d80-5881-11ea-8541-72e145d5a71a.png">

**Comment by davidforrest** [comment]
(none of the options were correct for this chord)

**Comment by jsbean** [comment]
We are going to remove the viio/vii for now. I think this may be the only chord with this issue. I will investigate, though.

**Comment by jsbean** [comment]
Ahh, I just ran into this with a different chord. Investigating…
