### ISSUE TITLE
Weight the generation of chord types equally

### ISSUE THREAD

**Issue by davidforrest** [1aurend/music51#46]
Kate does not want us to weight the generator toward the new (non-diatonic) chord types. 

Some students will be new to Chord Crusher, and they should have equal practice with all chord types, including those from previous modes.

We would want to choose equally from the four categories of chords:

- In-Key (ChordType.TRIAD and ChordType.SEVENTH)
- ChordType.CHROMATIC_VARIATION
- ChordType.MODE_MIXTURE
- ChordType.APPLIED_CHORD

Not from all the ChordStructures. Does that make sense?

**Comment by jsbean** [comment]
It makes sense. Mostly because this is how we are operating at the moment!
