### ISSUE TITLE
Toggles do not work on Safari?

### ISSUE THREAD

**Issue by jsbean** [1aurend/music51#62]
@1aurend, I am testing on Safari (v 13.0.1) on macOS Catalina Beta. It could be something about my system, but it may be worthwhile to test it out on Safari on another machine!

When I touch one of these toggles, they stretch. But no matter how hard I try, they won't flip to the other state.

When I test on Chrome, they work fine.

**Comment by 1aurend** [comment]
@jsbean Hmm... I do remember messing with these on different browsers months ago, but I don't remember the outcome. At any rate, the good news is we've gotten rid of them altogether in the new ui, so shouldn't be an issue!

**Comment by jsbean** [comment]
Oh right, I totally forgot about that 🤦‍♂ .
